name: SEU Auto Temperature Report
on:
  schedule:
    - cron: '20 23 * * *'
    # cron表达式，时区是UTC时间
  watch:
    types: started

jobs:
  Temperature_Report:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@main
      with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
    
    - name: Run
      env:
        TZ: Asia/Shanghai
        SEU_REPORT_INFORM: ${{ secrets.SEU_REPORT_INFORM }}
        BARK: ${{ secrets.BARK }}
        BARK_PUSH: ${{ secrets.BARK_PUSH }}
        SCKEY: ${{ secrets.SCKEY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        TG_API_HOST: ${{ secrets.TG_API_HOST }}
        TG_PROXY_IP: ${{ secrets.TG_PROXY_IP }}
        TG_PROXY_PORT: ${{ secrets.TG_PROXY_PORT }}
        DD_BOT_ACCESS_TOKEN: ${{ secrets.DD_BOT_ACCESS_TOKEN }}
        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
        QQ_SKEY: ${{ secrets.QQ_SKEY }}
        QQ_MODE: ${{ secrets.QQ_MODE }}
        QYWX_AM: ${{ secrets.QYWX_AM }}
        QYWX_KEY: ${{ secrets.QYWX_KEY }}
        PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
      run: |
        sudo apt-get install python3-setuptools -y
        git clone https://github.com/zys91/Actions-Report.git
        cp -r Actions-Report/* .
        pip3 install -r requirements.txt
        python3 auto_report.py
